if(CELEG_BUILD_TESTS)
    enable_testing()

    include(${CMAKE_CURRENT_LIST_DIR}/checkpoint/CMakeLists.txt)
    include(${CMAKE_CURRENT_LIST_DIR}/model/CMakeLists.txt)
    include(${CMAKE_CURRENT_LIST_DIR}/text/CMakeLists.txt)
    include(${CMAKE_CURRENT_LIST_DIR}/architecture/CMakeLists.txt)
    include(${CMAKE_CURRENT_LIST_DIR}/quality/CMakeLists.txt)
    include(${CMAKE_CURRENT_LIST_DIR}/api/CMakeLists.txt)
    include(${CMAKE_CURRENT_LIST_DIR}/quant/CMakeLists.txt)
    include(${CMAKE_CURRENT_LIST_DIR}/serve/CMakeLists.txt)
    include(${CMAKE_CURRENT_LIST_DIR}/vision/CMakeLists.txt)
    include(${CMAKE_CURRENT_LIST_DIR}/cpu/CMakeLists.txt)
    include(${CMAKE_CURRENT_LIST_DIR}/runtime/CMakeLists.txt)
    include(${CMAKE_CURRENT_LIST_DIR}/cuda/CMakeLists.txt)
    include(${CMAKE_CURRENT_LIST_DIR}/packed/CMakeLists.txt)

    include(${CMAKE_CURRENT_LIST_DIR}/metal/CMakeLists.txt)

    function(celeg_add_private_test_source_include_dirs)
        get_property(_celeg_test_targets DIRECTORY PROPERTY BUILDSYSTEM_TARGETS)
        foreach(_celeg_test_target IN LISTS _celeg_test_targets)
            if(_celeg_test_target MATCHES "(^|_)test$" OR _celeg_test_target MATCHES "_test$")
                target_include_directories(${_celeg_test_target} PRIVATE
                    ${CMAKE_CURRENT_SOURCE_DIR}/src)
            endif()
        endforeach()
    endfunction()
    cmake_language(DEFER CALL celeg_add_private_test_source_include_dirs)
endif()
