if(CELEG_BUILD_TESTS)
    enable_testing()

    function(celeg_include_test_manifest relative_path)
        set(_celeg_manifest "${CMAKE_CURRENT_LIST_DIR}/${relative_path}/CMakeLists.txt")
        if(EXISTS "${_celeg_manifest}")
            include("${_celeg_manifest}")
        else()
            message(WARNING "CELEG test manifest is missing: ${_celeg_manifest}")
        endif()
    endfunction()

    celeg_include_test_manifest(checkpoint)
    celeg_include_test_manifest(model)
    celeg_include_test_manifest(text)
    celeg_include_test_manifest(architecture)
    celeg_include_test_manifest(quality)
    celeg_include_test_manifest(api)
    celeg_include_test_manifest(quant)
    celeg_include_test_manifest(serve)
    celeg_include_test_manifest(vision)
    celeg_include_test_manifest(cpu)
    celeg_include_test_manifest(runtime)
    celeg_include_test_manifest(cuda)
    celeg_include_test_manifest(packed)
    celeg_include_test_manifest(metal)

    function(celeg_add_private_test_source_include_dirs)
        get_property(_celeg_test_targets DIRECTORY PROPERTY BUILDSYSTEM_TARGETS)
        foreach(_celeg_test_target IN LISTS _celeg_test_targets)
            if(_celeg_test_target MATCHES "(^|_)test$" OR _celeg_test_target MATCHES "_test$")
                target_include_directories(${_celeg_test_target} PRIVATE
                    ${CMAKE_CURRENT_SOURCE_DIR}/src)
            endif()
        endforeach()
    endfunction()
    cmake_language(DEFER CALL celeg_add_private_test_source_include_dirs)
endif()
