if(CELEG_BUILD_TESTS)
    enable_testing()

    function(celeg_include_test_manifest relative_path)
        set(_celeg_manifest "${CMAKE_CURRENT_LIST_DIR}/${relative_path}/CMakeLists.txt")
        if(NOT EXISTS "${_celeg_manifest}")
            message(FATAL_ERROR "CELEG test manifest is missing: ${_celeg_manifest}")
        endif()
        include("${_celeg_manifest}")
    endfunction()

    celeg_include_test_manifest(checkpoint)
    celeg_include_test_manifest(model)
    celeg_include_test_manifest(text)
    celeg_include_test_manifest(architecture)
    celeg_include_test_manifest(quality)
    celeg_include_test_manifest(api)
    celeg_include_test_manifest(quant)
    celeg_include_test_manifest(serve)
    celeg_include_test_manifest(vision)
    celeg_include_test_manifest(cpu)
    celeg_include_test_manifest(runtime)
    celeg_include_test_manifest(cuda)
    celeg_include_test_manifest(packed)
    celeg_include_test_manifest(metal)
endif()
