# Backend-independent checkpoint, model, text, and runtime support.
set(CELEG_BASE_RUNTIME_SOURCES
    src/checkpoint/formats/json.cpp
    src/checkpoint/formats/safetensors.cpp
    src/checkpoint/formats/gguf.cpp
    src/checkpoint/catalog.cpp
    src/checkpoint/metadata.cpp
    src/checkpoint/repositories/safetensors.cpp
    src/checkpoint/repositories/gguf.cpp
    src/checkpoint/downloader.cpp
    src/checkpoint/bootstrap.cpp
    src/model/definition.cpp
    src/model/architecture.cpp
    src/model/resolved.cpp
    src/model/program.cpp
    src/model/weight_plan.cpp
    src/model/graph_builder.cpp
    src/models/lfm2/architecture.cpp
    src/models/lfm2/layer_decoder.cpp
    src/models/lfm2/metadata_decoder.cpp
    src/models/lfm2/naming_policy.cpp
    src/models/lfm2/tool_call_codec.cpp
    src/models/granite/architecture.cpp
    src/models/granite/topology.cpp
    src/models/granite/naming_policy.cpp
    src/models/gemma4/architecture.cpp
    src/models/gemma4/naming_policy.cpp
    src/models/gemma4/tool_call_codec.cpp
    src/model/execution/runtime_types.cpp
    src/model/weights/quantization.cpp
    src/model/weights/roles.cpp
    src/model/reference.cpp
    src/text/tokenizer.cpp
    src/text/chat_template.cpp
    src/runtime/cache/pinned_expert_cache.cpp
    src/runtime/cache/prefix_radix.cpp
    src/runtime/cache/prefix_cache_index.cpp
    src/runtime/cache/prefix_cache.cpp
    src/runtime/concurrency/policy.cpp
    src/runtime/concurrency/metrics.cpp
    src/runtime/concurrency/request_registry.cpp
    src/runtime/concurrency/batch_planner.cpp
    src/runtime/concurrency/worker.cpp
    src/runtime/moe/reference.cpp
    src/runtime/moe/offload.cpp
)
