set(CELEG_CUDA_BACKEND_SOURCES
    src/backend/cuda/compiler.cpp
    src/backend/cuda/execution_plan.cpp
    src/backend/cuda/kernels/embedding.cu
    src/backend/cuda/kernels/transform.cu
    src/backend/cuda/kernels/attention.cu
    src/backend/cuda/kernels/sampling.cu
    src/backend/cuda/kernels/packed.cu
    src/backend/cuda/kernels/gguf.cu
    src/backend/cuda/kernels/mmq.cu
    src/backend/cuda/model/setup.cpp
    src/backend/cuda/model/configuration.cpp
    src/backend/cuda/model/resources.cpp
    src/backend/cuda/model/weight_setup.cpp
    src/backend/cuda/model/weight_validation.cpp
    src/backend/cuda/model/warmup.cpp
    src/backend/cuda/model/session_resources.cpp
    src/backend/cuda/model/lifecycle.cpp
    src/backend/cuda/model/residency.cu
    src/backend/cuda/model/execution.cu
    src/backend/cuda/model/sampler.cu
    src/backend/cuda/model/decode.cpp
    src/backend/cuda/model/prefill.cpp
    src/backend/cuda/model/prefill_batched.cpp
    src/backend/cuda/model/paged_prefill.cpp
    src/backend/cuda/model/prefill_profile.cpp
    src/backend/cuda/model/weights.cpp
    src/backend/cuda/model/packed_execution.cu
    src/backend/cuda/model/packed_workspace.cu
    src/backend/cuda/model/packed_commit.cpp
    src/backend/cuda/model/packed_metadata.cu
    src/backend/cuda/model/packed_layer_program.cpp
    src/backend/cuda/model/packed_operators.cu
    src/backend/cuda/model/packed_gemm_runtime.cpp
    src/backend/cuda/model/persistence.cu
    src/backend/cuda/model/facade.cu
    src/backend/cuda/model/weight_layout.cu
    src/backend/cuda/model/gguf_dequant.cpp
    src/backend/cuda/model/weight_upload.cpp
    src/backend/cuda/model/linear_loader.cpp
    src/backend/cuda/model/expert_loader.cpp
    src/backend/cuda/model/loader_experts.cu
    src/backend/cuda/model/experts.cu
    src/backend/cuda/model/loader_cache.cu
    src/backend/cuda/memory/paged_kv.cu
    src/backend/cuda/moe/host_expert_store.cu
    src/backend/cuda/moe/expert_layer_cache.cu
    src/backend/cuda/moe/ffn.cu
    src/backend/cuda/moe/route.cu
    src/backend/cuda/runtime/engine.cpp
    src/backend/cuda/runtime/request_lifecycle.cpp
    src/backend/cuda/runtime/prefill_scheduler.cpp
    src/backend/cuda/runtime/decode_scheduler.cpp
    src/backend/cuda/runtime/engine_control.cpp
    src/backend/cuda/runtime/engine_facade.cpp
    src/backend/cuda/runtime/gemm_dispatcher.cu
)
