#!/usr/bin/env bash
set -euo pipefail
ROOT="$(cd "$(dirname "$0")/.." && pwd)"
OUT="${TMPDIR:-/tmp}/lfm25-host-check"
rm -rf "$OUT"
mkdir -p "$OUT"
CXX="${CXX:-g++}"
CC="${CC:-cc}"
FLAGS=(-std=c++20 -Wall -Wextra -Wpedantic -I"$ROOT/include")

"$CXX" "${FLAGS[@]}" "$ROOT/src/json.cpp" "$ROOT/tests/json_test.cpp" -o "$OUT/json_test"
"$CXX" "${FLAGS[@]}" "$ROOT/src/json.cpp" "$ROOT/src/config.cpp" "$ROOT/tests/config_test.cpp" -o "$OUT/config_test"
"$CXX" "${FLAGS[@]}" "$ROOT/src/reference.cpp" "$ROOT/tests/reference_test.cpp" -o "$OUT/reference_test"
"$CXX" "${FLAGS[@]}" "$ROOT/tests/policy_test.cpp" -o "$OUT/policy_test"
"$CXX" "${FLAGS[@]}" "$ROOT/src/quantization.cpp" "$ROOT/tests/quantization_test.cpp" -o "$OUT/quantization_test"
"$CXX" "${FLAGS[@]}" "$ROOT/src/json.cpp" "$ROOT/src/tokenizer.cpp" "$ROOT/tests/tokenizer_test.cpp" -o "$OUT/tokenizer_test"
"$CXX" "${FLAGS[@]}" "$ROOT/src/json.cpp" "$ROOT/src/safetensors.cpp" "$ROOT/tests/safetensors_test.cpp" -o "$OUT/safetensors_test"
"$CC" -std=c11 -Wall -Wextra -Wpedantic -I"$ROOT/include" "$ROOT/tests/c_api_header_test.c" -o "$OUT/c_api_header_test"
"$CXX" "${FLAGS[@]}" "$ROOT/src/concurrent_policy.cpp" "$ROOT/tests/concurrent_policy_test.cpp" -o "$OUT/concurrent_policy_test"
"$CXX" "${FLAGS[@]}" "$ROOT/src/prefix_radix.cpp" "$ROOT/tests/prefix_radix_test.cpp" -o "$OUT/prefix_radix_test"
"$CXX" "${FLAGS[@]}" "$ROOT/src/concurrent_metrics.cpp" "$ROOT/tests/concurrent_metrics_test.cpp" -o "$OUT/concurrent_metrics_test"
"$CXX" "${FLAGS[@]}" "$ROOT/src/runtime_types.cpp" "$ROOT/src/execution_plan.cpp" "$ROOT/tests/execution_plan_test.cpp" -o "$OUT/execution_plan_test"
"$CXX" "${FLAGS[@]}" "$ROOT/src/runtime_types.cpp" "$ROOT/src/prefix_radix.cpp" "$ROOT/src/prefix_cache.cpp" "$ROOT/tests/prefix_cache_test.cpp" -o "$OUT/prefix_cache_test"
"$CXX" "${FLAGS[@]}" "$ROOT/tests/public_facade_test.cpp" -o "$OUT/public_facade_test"
"$CXX" "${FLAGS[@]}" "$ROOT/src/request_registry.cpp" "$ROOT/tests/request_registry_test.cpp" -o "$OUT/request_registry_test"
"$CXX" "${FLAGS[@]}" "$ROOT/src/request_registry.cpp" "$ROOT/src/batch_planner.cpp" "$ROOT/tests/batch_planner_test.cpp" -o "$OUT/batch_planner_test"
"$CXX" "${FLAGS[@]}" -pthread "$ROOT/src/engine_worker.cpp" "$ROOT/tests/engine_worker_test.cpp" -o "$OUT/engine_worker_test"
"$CC" -std=c11 -Wall -Wextra -Wpedantic -I"$ROOT/include" "$ROOT/tests/concurrent_c_api_header_test.c" -o "$OUT/concurrent_c_api_header_test"
"$CXX" "${FLAGS[@]}" "$ROOT/src/cpu_isa.cpp" "$ROOT/tests/cpu_isa_test.cpp" -o "$OUT/cpu_isa_test"
"$CXX" "${FLAGS[@]}" -pthread "$ROOT/src/cpu_topology.cpp" "$ROOT/src/cpu_thread_pool.cpp" "$ROOT/tests/cpu_thread_pool_test.cpp" -o "$OUT/cpu_thread_pool_test"
"$CXX" "${FLAGS[@]}" "$ROOT/src/quantization.cpp" "$ROOT/src/cpu_quantization.cpp" "$ROOT/tests/cpu_quantization_test.cpp" -o "$OUT/cpu_quantization_test"
"$CXX" "${FLAGS[@]}" -pthread "$ROOT/src/quantization.cpp" "$ROOT/src/cpu_isa.cpp" "$ROOT/src/cpu_topology.cpp" "$ROOT/src/cpu_thread_pool.cpp" "$ROOT/src/cpu_quantization.cpp" "$ROOT/src/cpu_kernels.cpp" "$ROOT/tests/cpu_kernels_test.cpp" -o "$OUT/cpu_kernels_test"
"$CXX" "${FLAGS[@]}" -pthread "$ROOT/src/quantization.cpp" "$ROOT/src/cpu_isa.cpp" "$ROOT/src/cpu_topology.cpp" "$ROOT/src/cpu_thread_pool.cpp" "$ROOT/src/cpu_quantization.cpp" "$ROOT/src/cpu_kernels.cpp" "$ROOT/tests/cpu_kv_cache_test.cpp" -o "$OUT/cpu_kv_cache_test"
"$CXX" "${FLAGS[@]}" -pthread "$ROOT/src/quantization.cpp" "$ROOT/src/cpu_numa.cpp" "$ROOT/src/cpu_topology.cpp" "$ROOT/src/cpu_thread_pool.cpp" "$ROOT/src/cpu_paged_kv.cpp" "$ROOT/tests/cpu_paged_kv_test.cpp" -o "$OUT/cpu_paged_kv_test"
"$CXX" "${FLAGS[@]}" -pthread "$ROOT/src/quantization.cpp" "$ROOT/src/cpu_numa.cpp" "$ROOT/src/cpu_topology.cpp" "$ROOT/src/cpu_thread_pool.cpp" "$ROOT/src/cpu_paged_kv.cpp" "$ROOT/tests/cpu_parallel_attention_test.cpp" -o "$OUT/cpu_parallel_attention_test"
"$CXX" "${FLAGS[@]}" -pthread "$ROOT/src/quantization.cpp" "$ROOT/src/cpu_numa.cpp" "$ROOT/src/cpu_topology.cpp" "$ROOT/src/cpu_thread_pool.cpp" "$ROOT/src/cpu_paged_kv.cpp" "$ROOT/src/prefix_radix.cpp" "$ROOT/src/cpu_prefix_cache.cpp" "$ROOT/tests/cpu_prefix_cache_test.cpp" -o "$OUT/cpu_prefix_cache_test"
"$CXX" "${FLAGS[@]}" "$ROOT/src/cpu_numa.cpp" "$ROOT/tests/cpu_numa_test.cpp" -o "$OUT/cpu_numa_test"
"$CC" -std=c11 -Wall -Wextra -Wpedantic -I"$ROOT/include" "$ROOT/tests/cpu_c_api_header_test.c" -o "$OUT/cpu_c_api_header_test"

"$OUT/json_test"
"$OUT/config_test"
"$OUT/reference_test"
"$OUT/policy_test"
"$OUT/quantization_test"
"$OUT/tokenizer_test"
"$OUT/safetensors_test"
"$OUT/c_api_header_test"
"$OUT/concurrent_policy_test"
"$OUT/prefix_radix_test"
"$OUT/concurrent_metrics_test"
"$OUT/execution_plan_test"
"$OUT/prefix_cache_test"
"$OUT/public_facade_test"
"$OUT/request_registry_test"
"$OUT/batch_planner_test"
"$OUT/engine_worker_test"
"$OUT/concurrent_c_api_header_test"
"$OUT/cpu_isa_test"
"$OUT/cpu_thread_pool_test"
"$OUT/cpu_quantization_test"
"$OUT/cpu_kernels_test"
"$OUT/cpu_kv_cache_test"
"$OUT/cpu_paged_kv_test"
"$OUT/cpu_parallel_attention_test"
"$OUT/cpu_prefix_cache_test"
"$OUT/cpu_numa_test"
"$OUT/cpu_c_api_header_test"
"$ROOT/scripts/architecture_check.sh"
echo "host_check: all tests passed"
